/* Configuration for yeison_12 generated by Alire */
#ifndef YEISON_12_CONFIG_H
#define YEISON_12_CONFIG_H

#define CRATE_VERSION "0.2.0-dev"
#define CRATE_NAME "yeison_12"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  2

#endif
