name = "yeison_dev"
description = "Developer crate for Yeison 2012 and Yeison 2022"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <amosteo@unizar.es>"]
maintainers-logins = ["mosteo"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["testing-only"]

[[test]]
runner = "alire"
directory = "yeison_12/tests"

[[test]]
runner = "alire"
directory = "yeison_22/tests"
