name = "dev"
description = ""
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["dev"]

[build-profiles]
"*" = "validation"

[[depends-on]]
yeison_12 = "~0.2.0-dev"
yeison = "~0.2.0-dev"

[[pins]]
yeison_12 = { path='../yeison_12' }
yeison = { path='../yeison_22' }
