name = "yeison"
description = "A JSON-like data structure using Ada 2022 features"
version = "0.2.0-dev"
licenses = "MIT"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
tags = ["json", "yaml", "toml", "containers"]
website = "https://github.com/mosteo/yeison"

[build-switches]
"*".ada_version = "Ada12"
